### ISSUE TITLE
HTTP response error429 - Yahoo Finance

### ISSUE THREAD

**Issue by ForosArgBursatil** [adrianmichel/yloader#20]
Hi everyone! I feel this is bad news from Yahoo... ERROR 429, yes again, so cross fingers...
Let's hope there is a solution...
![06-03--2024_10-42-35](https://github.com/adrianmichel/yloader/assets/8614903/2eb4dbbe-8233-4c0c-8294-2187ba85e3ba)

**Comment by f3r15ka** [comment]
I Have the same problem (HTTP response error429).
Please help.

**Comment by pablokaegi** [comment]
Hello everyone, I have the same problem with error 429. Please help-me.

**Comment by amiralshoq** [comment]
I Have the same problem (HTTP response error429

**Comment by amiralshoq** [comment]
![3](https://github.com/adrianmichel/yloader/assets/171358605/c890246e-9760-4fb4-a7c2-d5e4db9684db)

**Comment by toddao** [comment]
timingsolution fixed this on their yahoo downloader
I did an auto install of json viewer.

**Comment by adilpr** [comment]
![image](https://github.com/adrianmichel/yloader/assets/135330603/639a2d83-5a5f-4260-b910-d0fb397c7e8c)




How do i resolve this error in yloader. Adrian suggested to wait and it should resolve. Its still not resolved. 

If timingsolution fixed this on their yahoo downloader then yloader should also fix this.

Thanks.

**Comment by toddao** [comment]
On Tue, 04 Jun 2024 23:01:48 -0700, you wrote:
I let the programmer at timingsolution.com fix it for me.  His name is
Sergey .  He will help you, nice guy.

>![image](https://github.com/adrianmichel/yloader/assets/135330603/639a2d83-5a5f-4260-b910-d0fb397c7e8c)
>
>
>> timingsolution fixed this on their yahoo downloader I did an auto install of json viewer. On Fri, 31 May 2024 12:14:32 -0700, you wrote:
>> [](#)
>> Hello everyone, I have the same problem with error 429. Please help-me.
>
>If you could elaborate how you resolved "HTTP response error429
>Thanks.

**Comment by MaciejJer** [comment]
> On Tue, 04 Jun 2024 23:01:48 -0700, you wrote: I let the programmer at timingsolution.com fix it for me. His name is Sergey . He will help you, nice guy.
> […](#)
> ![image](https://github.com/adrianmichel/yloader/assets/135330603/639a2d83-5a5f-4260-b910-d0fb397c7e8c) > timingsolution fixed this on their yahoo downloader I did an auto install of json viewer. On Fri, 31 May 2024 12:14:32 -0700, you wrote: > [�](#) > Hello everyone, I have the same problem with error 429. Please help-me. If you could elaborate how you resolved "HTTP response error429 Thanks.

Does it mean we need to get some update ?I am getting same issue, but so far not clear how to solve it and how did you solve it ?

**Comment by adilpr** [comment]
> > On Tue, 04 Jun 2024 23:01:48 -0700, you wrote: I let the programmer at timingsolution.com fix it for me. His name is Sergey . He will help you, nice guy.
> > […](#)
> > ![image](https://private-user-images.githubusercontent.com/135330603/336705315-639a2d83-5a5f-4260-b910-d0fb397c7e8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzQ3MjQsIm5iZiI6MTcxNzY3NDQyNCwicGF0aCI6Ii8xMzUzMzA2MDMvMzM2NzA1MzE1LTYzOWEyZDgzLTVhNWYtNDI2MC1iOTEwLWQwZmIzOTdjN2U4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMTQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjI1NGMxMWFjYjQ2ZmZkZjZiOWYxNjg0NzNmZjU1NDIzY2JmODJkMDlhMTk3ZmQ1NGE4NTliMjQ0YWQ3OGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mvnethdH62KNb8ksu_jTuBOa-p1B1UDfvF4BCYXPTmQ) > timingsolution fixed this on their yahoo downloader I did an auto install of json viewer. On Fri, 31 May 2024 12:14:32 -0700, you wrote: > [�](#) > Hello everyone, I have the same problem with error 429. Please help-me. If you could elaborate how you resolved "HTTP response error429 Thanks.
> 
> Does it mean we need to get some update ?I am getting same issue, but so far not clear how to solve it and how did you solve it ?

I use the paid version of Amiquote ( www.amibroker.com). which allows to download from yahoo eod.

yloader is still unsolved...

toddao  :I donot have timingsolution.com paid software. will Sergey still help?

**Comment by toddao** [comment]
ask, he's a nice guy,
ask his support staff, at least try

yloader had this kind of problem a few years ago , it took roughly a
month for the software writer to get around to it. (see old emails) 
The writer who wrote yloader and at that time wanted to walk away and
concentrate on his real job.   Concentrate on finding his real email
and not the one on github.

**Comment by Rahmengo** [comment]
As of 2024-06-13 I am still getting the HTTP response error429.
Would be great if someone can point me in the right direction on how to fix this and I will give it a try myself.

**Comment by toddao** [comment]
timingsolution.com had this same , exact problem.  Fixed in a day.

write them and ask.   Main programmer is Sergey, there are others
there too who would know the answer.  They are nice people, no
gauntest.  They are busy folks,

PS I have written this same info in this thread multiple times over
the last several weeks.

**Comment by ForosArgBursatil** [comment]
Thank you very much Adrian! Always willing to solve the problem and keep the application updated ;)

**Comment by adilpr** [comment]
Thank you very much Adrian...


![image](https://github.com/user-attachments/assets/ad447db1-be3f-45de-bf09-4e52b56fbb2b)

**Comment by irisheyesaremine** [comment]
Did this issue gat resolved? I see that some have thanked Adrian...mine is still not working...Thank you.
